import mongoose from 'mongoose';
import Trek from './models/Trek.js';
import Guide from './models/Guide.js';
import dotenv from 'dotenv';

dotenv.config();

mongoose.connect(process.env.MONGODB_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
})
  .then(async () => {
    console.log('Connected to MongoDB');

    await Trek.deleteMany({});
    await Guide.deleteMany({});

    const treks = [
      {
        name: 'Valley of Flowers',
        location: 'Chamoli, Uttarakhand',
        lat: 30.7281,
        lon: 79.6052,
        duration: 6,
        difficulty: 'moderate',
        price: 18500,
        rating: 4.8,
        reviewCount: 234,
        maxGroupSize: 15,
        description: 'A UNESCO World Heritage site blanketed with alpine wildflowers every monsoon. The valley stretches over 87 sq km at an elevation of 3,658m, flanked by towering Himalayan peaks. Witness hundreds of species of flowering plants including the rare Brahmakamal. The trail passes through lush forests, glacial streams, and pristine meadows.',
        isEcoFriendly: true,
        season: 'summer',
        popularity: 95,
        image: 'https://upload.wikimedia.org/wikipedia/commons/6/63/Valley_of_flowers_uttaranchal_full_view.JPG',
      },
      {
        name: 'Kedarkantha Trek',
        location: 'Uttarkashi, Uttarakhand',
        lat: 31.0134,
        lon: 78.1719,
        duration: 5,
        difficulty: 'easy',
        price: 12500,
        rating: 4.7,
        reviewCount: 312,
        maxGroupSize: 20,
        description: 'One of the finest winter treks in India, Kedarkantha summit stands at 3,810m offering a 360° panoramic view of Himalayan peaks including Swargarohini, Bandarpoonch, and Black Peak. The trail winds through dense pine and oak forests draped in snow, magical campsites at Juda Ka Talab and Kedarkantha Base.',
        isEcoFriendly: true,
        season: 'winter',
        popularity: 92,
        image: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Kedarkantha_Trek.jpg',
      },
      {
        name: 'Roopkund Trek',
        location: 'Chamoli, Uttarakhand',
        lat: 30.2623,
        lon: 79.7317,
        duration: 8,
        difficulty: 'hard',
        price: 25000,
        rating: 4.9,
        reviewCount: 178,
        maxGroupSize: 12,
        description: 'The mystery lake at 5,029m holds ancient skeletal remains dating to the 9th century, surrounded by glaciated peaks and vast meadows of Ali Bugyal and Bedni Bugyal. Challenging high-altitude sections, steep ridgelines, and breathtaking views of Trishul and Nanda Ghunti peaks make this a bucket-list Himalayan adventure.',
        isEcoFriendly: true,
        season: 'summer',
        popularity: 98,
        image: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Roopkund_Lake.jpg',
      },
      {
        name: 'Har Ki Dun',
        location: 'Uttarkashi, Uttarakhand',
        lat: 31.1646,
        lon: 78.4028,
        duration: 7,
        difficulty: 'moderate',
        price: 16000,
        rating: 4.6,
        reviewCount: 145,
        maxGroupSize: 18,
        description: 'A stunning cradle-shaped hanging valley at 3,566m, Har Ki Dun is surrounded by Swargarohini massif and Fateh Parvat. The trail passes through quaint Govind National Park, ancient villages with Kauravar mythology links, dense rhododendron forests, and the pristine Tons river valley.',
        isEcoFriendly: true,
        season: 'spring',
        popularity: 80,
        image: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Entering_Har_Ki_Dun.JPG',
      },
      {
        name: 'Chopta Tungnath Chandrashila',
        location: 'Rudraprayag, Uttarakhand',
        lat: 30.4794,
        lon: 79.2105,
        duration: 4,
        difficulty: 'easy',
        price: 9500,
        rating: 4.7,
        reviewCount: 267,
        maxGroupSize: 25,
        description: 'Known as the "Mini Switzerland of Uttarakhand", Chopta is a pristine meadow at 2,680m. The trek to Tungnath (highest Shiva temple in the world at 3,680m) and Chandrashila summit (4,130m) offers spectacular views of Nanda Devi, Trishul, Kedarnath, and Chaukhamba peaks.',
        isEcoFriendly: true,
        season: 'spring',
        popularity: 88,
        image: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Bugyals_enroute_Tungnath.jpg',
      },
      {
        name: 'Pangarchulla Peak',
        location: 'Chamoli, Uttarakhand',
        lat: 30.5634,
        lon: 79.5812,
        duration: 6,
        difficulty: 'hard',
        price: 22000,
        rating: 4.8,
        reviewCount: 98,
        maxGroupSize: 10,
        description: 'A thrilling summit trek to 4,700m in the Kumaon Himalayas, Pangarchulla offers dramatic views of Nanda Devi, Dronagiri, and Hathi Ghoda peaks. The approach through Joshimath and the iconic Khulara campsite make this a prized objective for experienced trekkers seeking a genuine Himalayan peak.',
        isEcoFriendly: true,
        season: 'spring',
        popularity: 75,
        image: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Pangarchulla_Peak.jpg',
      },
      {
        name: 'Kuari Pass Trek',
        location: 'Chamoli, Uttarakhand',
        lat: 30.5147,
        lon: 79.6503,
        duration: 6,
        difficulty: 'moderate',
        price: 17500,
        rating: 4.7,
        reviewCount: 163,
        maxGroupSize: 16,
        description: "First opened by Lord Curzon in the early 1900s, the Curzon Trail to Kuari Pass (3,640m) is one of the grandest Himalayan walks. The trail unveils a continuous panorama of over 20 Himalayan peaks — Nanda Devi, Kamet, Mana, Dronagiri, and Chaukhamba — visible from the open meadows and ridgeline camps.",
        isEcoFriendly: true,
        season: 'autumn',
        popularity: 83,
        image: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Kuari_Pass_Bugyal_2.jpg',
      },
      {
        name: 'Brahmatal Trek',
        location: 'Chamoli, Uttarakhand',
        lat: 30.3961,
        lon: 79.5284,
        duration: 6,
        difficulty: 'moderate',
        price: 14000,
        rating: 4.6,
        reviewCount: 121,
        maxGroupSize: 20,
        description: 'A beautiful winter high-altitude lake trek to Brahmatal (3,712m) and Brahmatal summit (4,246m). The frozen lake surrounded by snow-laden oak and rhododendron forests with unobstructed views of Mt Trishul and Nanda Ghunti makes it one of the finest winter treks in the Garhwal Himalayas.',
        isEcoFriendly: true,
        season: 'winter',
        popularity: 78,
        image: 'https://upload.wikimedia.org/wikipedia/commons/2/27/Brahmatal.jpg',
      },
      {
        name: 'Nag Tibba Trek',
        location: 'Tehri, Uttarakhand',
        lat: 30.6512,
        lon: 78.2598,
        duration: 2,
        difficulty: 'easy',
        price: 5500,
        rating: 4.4,
        reviewCount: 389,
        maxGroupSize: 30,
        description: 'The highest peak in the lower Himalayan ranges of Garhwal at 3,022m, Nag Tibba is perfect for beginners and weekend trekkers from Delhi/Dehradun. The summit offers panoramic views of Gangotri, Kedarnath, Yamunotri, and Bandarpoonch ranges through dense forests of oak, rhododendron, and ferns.',
        isEcoFriendly: true,
        season: 'winter',
        popularity: 85,
        image: 'https://upload.wikimedia.org/wikipedia/commons/9/94/A_panoramic_view_of_Himalayan_peaks_Himachal_Pradesh_India_Nag_Tibba_summit_December_2014.jpg',
      },
      {
        name: 'Dayara Bugyal',
        location: 'Uttarkashi, Uttarakhand',
        lat: 30.9312,
        lon: 78.5167,
        duration: 5,
        difficulty: 'easy',
        price: 11000,
        rating: 4.5,
        reviewCount: 198,
        maxGroupSize: 22,
        description: 'One of the most beautiful high-altitude meadows (bugyals) in India at 3,408m, Dayara Bugyal transforms into a snow-white paradise in winter and a carpet of green and flowers in summer. The wide open meadows offer sweeping views of Bandarpoonch, Gangotri Group, and Janoli peaks.',
        isEcoFriendly: true,
        season: 'autumn',
        popularity: 77,
        image: 'https://upload.wikimedia.org/wikipedia/commons/5/56/Dayara_Bugyal_2.jpg',
      },
    ];

    const guides = [
      {
        name: 'Rajesh Kumar',
        image: 'https://picsum.photos/seed/rajesh/300/300',
        rating: 4.8,
        reviewCount: 127,
        experience: 8,
        location: 'Rishikesh',
        specialties: ['Valley of Flowers', 'Har Ki Dun', 'Kedarkantha'],
        languages: ['Hindi', 'English', 'Garhwali'],
        phone: '+91 9876543210',
        email: 'rajesh@ecotrek.com',
        pricePerDay: 2500,
        availability: 'Available',
        totalTrips: 250,
        certifications: ['Wilderness First Aid', 'Mountain Guide Level 2'],
      },
      {
        name: 'Priya Sharma',
        image: 'https://picsum.photos/seed/priya/300/300',
        rating: 4.9,
        reviewCount: 89,
        experience: 6,
        location: 'Uttarkashi',
        specialties: ['Roopkund', 'Pangarchulla', 'Kuari Pass'],
        languages: ['Hindi', 'English'],
        phone: '+91 9876543211',
        email: 'priya@ecotrek.com',
        pricePerDay: 2800,
        availability: 'Busy until March 15',
        totalTrips: 180,
        certifications: ['Advanced Mountaineering', 'Rescue Operations'],
      },
      {
        name: 'Deepak Negi',
        image: 'https://picsum.photos/seed/deepak/300/300',
        rating: 4.7,
        reviewCount: 203,
        experience: 12,
        location: 'Joshimath',
        specialties: ['Brahmatal', 'Chopta Tungnath', 'Dayara Bugyal'],
        languages: ['Hindi', 'English', 'Garhwali', 'Kumaoni'],
        phone: '+91 9876543212',
        email: 'deepak@ecotrek.com',
        pricePerDay: 3000,
        availability: 'Available',
        totalTrips: 410,
        certifications: ['National Mountain Guide', 'High Altitude Medicine', 'Wilderness First Responder'],
      },
    ];

    await Trek.insertMany(treks);
    await Guide.insertMany(guides);

    console.log('Database seeded: 10 treks, 3 guides');
    mongoose.connection.close();
  })
  .catch((err) => {
    console.error('Error:', err);
    mongoose.connection.close();
  });
